---
title: "blog"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(robotstxt) 
library(rvest) 
library(purrr)
library(janitor)
library(maps)
library(sf)
library(ggspatial)
library(DT)
library(RColorBrewer)
library(fuzzyjoin)
library(leaflet)
library(leaflegend)
```

## R Markdown

```{r cars}
## Import Data
map <- read.delim(file = "/Users/sara/Desktop/STAT231/stat231-content/master_df.txt", header=TRUE, sep="\t") 

report_card <- read.delim(file = "/Users/sara/Desktop/STAT231/stat231-content/school_scores.txt", header=TRUE, sep="\t") 

clean_answers <- read_csv("/Users/sara/Desktop/STAT231/stat231-content/scrape.csv")
```

```{r}
map <- schools
```


```{r}
# Make list of icons
medalIcons <- iconList(
  Platinum = makeIcon(iconUrl = "icons/platinum.png",
                      iconWidth = 15, iconHeight = 15),
  Gold = makeIcon(iconUrl = "icons/gold.png",
                      iconWidth = 10, iconHeight = 11),
  Silver = makeIcon(iconUrl = "icons/silver.png",
                      iconWidth = 10, iconHeight = 11),
  Bronze = makeIcon(iconUrl = "icons/bronze.png",
                      iconWidth = 10, iconHeight = 11)
)

leaflet(data = map) %>% 
  addTiles() %>%
  addMarkers(~long, 
             ~lat, 
             icon = ~medalIcons[rating],
             popup = ~institution,
             #clusterOptions = markerClusterOptions()
             ) %>% 
  addLegendImage(c('icons/platinum.png','icons/gold.png', 
                   'icons/silver.png', 'icons/bronze.png'), 
                 title = htmltools::tags$div('schools',
       style = 'font-size: 14px; text-align: center; margin-bottom: 5px;'), 
                 labels = c("Platinum", "Gold", "Silver", "Bronze"),
                 labelStyle = "font-size:12px")
```


```{r}
pal <- colorFactor(c("#7aa7d6", "#f0dd60", "#9e9e9e", "#ba8a65"), 
                   domain = c("Platinum", "Gold", "Silver", "Bronze"))

leaflet(data = map) %>% 
  addTiles() %>%
  addCircleMarkers(
    ~long,
    ~lat,
    popup = ~institution,
    radius = 3,
    color = ~pal(rating),
    stroke = FALSE, fillOpacity = 0.9
  ) %>%
  addLegend("bottomright",
            values = ~rating,
            colors = c("#7aa7d6", "#f0dd60", "#9e9e9e", "#ba8a65"),
            labels = c("Platinum", "Gold", "Silver", "Bronze"),

    title = "schools",
    opacity = 1
  )

```
 




